/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: do not edit it. Instead, edit the BAML
// files and re-generate this code.
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code
const fileMap = {
  
  "main.baml": "generator target {\r\n  output_type \"typescript\"\r\n  output_dir \"../src\"\r\n  version \"0.58.0\"\r\n}\r\n\r\nenum OrderDecision {\r\n  Approve\r\n  Review\r\n  Reject\r\n}\r\n\r\nclass Classification {\r\n  decision OrderDecision\r\n  reason string\r\n  confidence float\r\n}\r\n\r\nfunction ClassifyOrder(input: string) -> Classification {\r\n  client \"openai/gpt-4o-mini\"\r\n  prompt #\"\r\n    Analyze this inventory data for Order:\r\n    {{input}}\r\n\r\n    Decide if we should Approve, Review, or Reject.\r\n    Return JSON.\r\n  \"#\r\n}",
}
export const getBamlFiles = () => {
    return fileMap;
}